version: "3"

services:
  broker:
    image: sphinxlightning/sphinx-broker:latest
    restart: on-failure
    container_name: broker.sphinx
    environment:
      - SEED=8A048DC1F0020127E0E8DD72ACEFC62B8A048DC1F0020127E0E8DD72ACEFC62B
      - NETWORK=regtest
      - BROKER_MQTT_PORT=1883
    ports:
      - 1883:1883

  mixer:
    image: sphinxlightning/sphinx-mixer:latest
    restart: on-failure
    container_name: mixer.sphinx
    environment:
      - TESTING_ONLY_ADD_TO_SENDER=1
      - SEED=8A048DC1F0020127E0E8DD72ACEFC62B8A048DC1F0020127E0E8DD72ACEFC62B
      - NETWORK=regtest
      - BROKER_URL=broker.sphinx:1883
      - NO_GATEWAY=true
      - NO_LIGHTNING=true
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=8888
      - DB_PATH=/home/data
      - ADMIN_ROUTES=true
    ports:
      - 8888:8888

  alice:
    image: sphinxlightning/sphinx-bot:latest
    restart: on-failure
    container_name: alice.sphinx
    environment:
      - PORT=3001
      - SEED=8DDDB00FFDE4581983FAA55AED83560486874391FDF93776DBBABBFE1C243C14
      - NETWORK=regtest
      - BROKER=http://broker.sphinx:1883
      - MY_ALIAS=ALICE
      - ADMIN_TOKEN=xyzxyzxyz
      - INITIAL_DELAY=5000
    ports:
      - 3001:3001

  bob:
    image: sphinxlightning/sphinx-bot:latest
    restart: on-failure
    container_name: bob.sphinx
    environment:
      - PORT=3002
      - SEED=7A9039255E3776858BDF7E51B840ED795F99FCF0358C201BAAC4AB1FEB45C236
      - NETWORK=regtest
      - BROKER=http://broker.sphinx:1883
      - MY_ALIAS=BOB
      - ADMIN_TOKEN=xyzxyzxyz
      - INITIAL_DELAY=5000
    ports:
      - 3002:3002
